nasa/HyperCP

Main.py
environment.yaml

Download size is fetched from the server instead of using a hardcoded one and a progress bar is displayed with net info while downloading.

 Progress bar and download size retrieve

---

Source/Utilities.py

Round degrees to avoid floating point problems

---

Source/Utilities.py

Corrections to degree conversion utility

---

Changelog.md

Addresses Issue: Test issue
The only change is a line in Chagelog.md
No behavioral changes to main code
No bugs addressed
Dirk Aurin, oceancolorcoder, NASA/GSF

Test fork branch PR to TestBranch

---

Main.py
Source/Controller.py
Source/OCproductsWindow.py
Source/ProcessL1aqc.py
Source/ProcessL2.py
Source/ProcessL2BRDF.py
Source/RhoCorrections.py
Source/Utilities.py
Source/ZhangRho.py
run.py

Speedup Zhang et al. 2017 correction and other minor improvements

---

Changelog.md

Issue created on main repo. 
Fork and for branch created. 
Edits made to Changelog and committed.
Submission of PR will successfully complete testing.

Fix #21 Demo the Issue-Fork-Branch-PR

---

HyperCP_Project_guidelines.md
HyperCP_Project_guidelines_APPENDIX.md

Added HyperCP Project Guidelines + appendix
Testing: not required

Fix #30 (partially), added HyperCP Project Guidelines

---

Source/ProcessL1b.py
Source/ProcessL1b_FRMCal.py
Source/TriosL1B.py
Source/Utilities.py

Update of the characterisation file reading for FRM process. The process run up to L2 and L1B HDF files have the complete list of characterization coefficients including uncertainties.

update full characterisation files reading process (issue #36)

---

Source/GetAnc_ecmwf.py

Note : there is a new error in processL1B, linked to AOD wavelength, but ECMWF ancillary data from 12 hour is still downloaded on my side.

fix timestamp computation for ECMWF

---

Source/ProcessL1b.py
Source/TriosL1B.py
Source/Utilities.py

class uncertainty ingested for seabird.
class based radiometric processing running up to L1B (same as factory with update coefficient)

class based processing for Seabird with class radcal unc (issue #35)

---

Source/AnomalyDetection.py

This is what I see now. Hope it works :)
If zoomed out, it will show instead months/days/years ...

Solved time stamp issue?

---

Source/Controller.py
Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FRMCal.py
Source/TriosL1B.py
Source/Utilities.py

- Fix the calling of cosine correction for Trios L1B
- The L1BQC filtering fix is only temporary, there probably a better way to do it. see modification in utlities.filterdata

fix cosine correction & L1BQC filtering

---

README_configuration.md
Source/ProcessInstrumentUncertainties.py
Source/TriosL1B.py

Error in float conversion factor 65535
Update readme to mention class-based process  in factory

Bug correction

---

Source/ConfigWindow.py
Source/FidradDB_api.py
Source/ProcessL1b.py
Source/TriosL1B.py
environment.yml

FidRadDB is now available as a conda package.
Full characterization files are downloaded automatically.
Environment has been updated with new package (and tested).
This solve the issue #50

Activation of FidRadDB (issue #50)

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FactoryCal.py
Source/ProcessL2.py

seabird factory now has Rrs_unc based on class-based + SIRREX files

fix seabird factory uncertainty (issue #84)

---

Source/ProcessInstrumentUncertainties.py
Source/Utilities.py

This fix the high uncertainty value for Seabird-Factory (issue #84)

fix factory unc interpolation error

---

Source/FidradDB_api.py

change in ocdb url for fidraddb access

fix FidRadDB access

---

.github/workflows/build.yml
README_bundle.md

+ App is bundled automatically on Ubuntu, macOS, and Windows
+ macOS app is NOT signed, look at README_bundle.md to bypass macOS gatekeeper (requires sudo)
+ App will be compiled on any commit to the main, dev, or workflow branch
+ Linked to Pull Request #81

Added GitHub Workflow to automatically bundle application

---

Main.py
Source/FidradDB_api.py
Source/ProcessL1b.py
Source/TriosL1B.py

Issue 136 (commit 0ba2f94): All paths in Main.py now referred to CODE path - via os.path.cwd, hence Main.py can be run from any working directory. This should prevent users running into issues when running from other directories
Issue 119 (commit 16c3fdd): FidRadDB downloads now working properlyFidRadDB downloads now organised into single directory for each sensor type (SeaBird and TriOS). Clash with Ashley's PR solved.

Solve Issues #136 and 119

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FRMCal.py
Source/TriosL1B.py

to test issue #122 
Zong now done per default
Uncertainties implementation to be check by NPL

implementation of Zong straylight correction (issue #122)

---

Source/ProcessL1b_FRMCal.py
Source/ProcessL1b_Interp.py
Source/TriosL1B.py

creation of py6s group to store data at L1B & L1BQC levels

add py6s group to store model irradiance (issue #145)

---

Source/ProcessL2.py
Source/RhoCorrections.py

Fixed a bug in processL2 which was effecting data with casts exceeding the Ensemble Interval. Also added comment to clarify propagate object in Z17.

Tiny bugfix

---

Source/ProcessInstrumentUncertainties.py

Fixed bug caused by negative uncertainty values in Default and Factory branch

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FRMCal.py
Source/TriosL1B.py

- Zong used and L1B
- Slaper used for uncertainties

re-enabled slapper for FRM uncertainties to fix FRM issues.

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FactoryCal.py
Source/ProcessL2.py

Changes:
- function added to L1B to read calibration file start and stop points. 
- Cal start/stop applied to the Factory L2 uncertainty processing to slice straylight uncertainty.
- fixed bug caused in L2 processing when outputting Rho Uncertainty to .hdf file.
- Windspeed uncertainty changed to 2m/s.
- added comments.

Factory branch processing for calibration less than 256 pixels

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FRMCal.py
Source/TriosL1B.py

Fetched and merged with latest  dev branch - applied fix for Zong uncertainty spikiness. Zong uncertainties re-enabled in ProcessL1b_FRMCal, Trios1B and ProcessInstrumentUncertainties.

Zong correction re-enabled, spikiness in uncertainty output corrected.

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FRMCal.py
Source/ProcessL1b_Interp.py
Source/ProcessL1bqc.py
Source/ProcessL2.py
Source/TriosL1B.py

This commit will allow Ashley to read the py6s dataset a L2

add reading function for py6s results in PIU.py

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FRMCal.py
Source/RhoCorrections.py
Source/TriosL1B.py
Source/Uncertainty_Analysis.py
Source/Uncertainty_Visualiser.py

- Implemented Alexis' Py6s read function into ProcessInstrumentUncertainties, forgoing second Py6s.run_wavelengths call.
- Implemented OS check, if windows detected then run_wavelengths is run with n=1 (n=None otherwise) which works to solve issue #121. 
- uncertainty_Visualiser added with basic functionality for FRM uncertainty plotting.
- Fixed bug where dark subtraction was done twice in certain circumstances during L2 uncertainty processing. 
- Cleaned up some irrelevant comments in ProcessInstrumentUncertainties.

ProcessL2 optimisation and bugfixing

---

Source/ocbrdf/main.py

FIX: Bug introduced in #2bf5e6f071c5d4b084f2d71b897d7c9beed2f81b (BRDF harmonisation).
Convergence condition was wrongly expressed and affecting all schemes, now corrected.

Fix BUG in the BRDF 'harmonised' implementation.

---

Source/ProcessInstrumentUncertainties.py
Source/ProcessL1b_FactoryCal.py
Source/ProcessL1bqc.py
Source/ProcessL2.py
Source/ProcessL2BRDF.py
Source/RhoCorrections.py
Source/Uncertainty_Analysis.py
Source/Uncertainty_Visualiser.py
Source/Utilities.py

Reverts nasa/HyperCP#196
PR submitted to master.

Revert "Bugfixes, uncertainty plots and M99 bugfix"

---

Source/ProcessL1b_FRMCal.py

this solve the "short cast" case of issue #203 seen for Trios example.
this does not solve the NAN issue seen for NASA cast FRM4SOC2_FICE22_NASA_20220719_100000_L1BQC

fix py6s interpolation in case with only 1 bin

---

Source/ocbrdf/brdf_model_L11.py
Source/ocbrdf/brdf_model_M02.py
Source/ocbrdf/brdf_model_M02SeaDAS.py
Source/ocbrdf/brdf_model_O23.py
Source/ocbrdf/brdf_utils.py
Source/ocbrdf/ocbrdf_main.py

Also indirectly validated in ThoMaS using 30 matchups between MOBY and S3A (BRDF correction effect in matchups as expected according to BRDF4OLCI PVR).

ocbrdf: several minor adaptations to make it work on both HyperCP and ThoMaS. M02: Added computation of Irradiance reflectance. Tested both L11, M02.

---

Source/ProcessL1b_FRMCal.py

Minor fix to properly display 6S wavelength NaN debugging

Change 6S NaN to loging debug and fixed wl indices

---

.github/actions/SetupEnvironment/action.yml
.github/workflows/ApplicationTesting.yml
.github/workflows/Build.yml
.github/workflows/SetupEnvironment.yml
Main.py
Source/Utilities.py
run_Sample_Data.py

- run __run_Sample_Data.py__ on macOS, Windows, and Linux every time push on dev or master branch. Primitive test of application. Results of run can be seen in Actions > ApplicationTesting.
- refactored "Setup Environment" steps into composite action to reuse code from Bundle in ApplicationTesting
- force download of Zhang in command mode as cannot open QWidget to prompt user as QApplication is not started (also likely running without X)
- fix missing directory "Logs" on first run from command line

Add Application Testing Workflow

---

Source/Controller.py
Source/ProcessInstrumentUncertainties.py
Source/ProcessL1bTriOS.py
Source/ProcessL1b_FRMCal.py
Source/ProcessL1b_FactoryCal.py
Source/ProcessL1b_Interp.py
Source/ProcessL1bqc.py
Source/ProcessL2.py
Source/Utilities.py
environment.yml

Re-implementation of j6s on the latest dev branch.
The environment file will create an environment named hypercp_j6s. That way, you can test and compare the results with the two different environments.

j6s implementation (tested on ubuntu)

---

Main.py
Source/CalibrationFileReader.py
Source/ConfigWindow.py
Source/Controller.py
Source/ProcessL1aqc.py
Source/Utilities.py

Finished ProcessL1aqc step for dalec:
ProcessL1aqc.py:
Updated the script to work for dalec
Utilities.py:
Updated rootAddDateTime() function to work with dalec.
Rest of the changes are from the pull from nasa/dev

ProcessL1aqc step for dalec & updates from dev branch

---

Source/GetAnc_ecmwf.py

Tested on TriOS and pySAS sample datasets

ECMWF Ancillary: Minor bug Fix

---

Source/GetAnc_ecmwf.py
Source/ProcessInstrumentUncertainties.py
Source/ProcessL1aTriOS.py
Source/RhoCorrections.py
Source/Uncertainty_Analysis.py
build_Z17-LUT.py

Tested on PySAS solartracker and Trios notracker sample datasets for:
- FRM
- Class-Based 
- Z17
- M99
Same as PR before except with the excess cut. I did have an issue in that an error fix I implemented for Juan's ecmwf datetime issue got mixed into the commits. There is a commit at the end which address this. Also the last commit has very similar name, this was because I amended it to the one before but the push ended up reverting this. Hopefully it will not be too much trouble to merge.

Ammended PR

---

Source/ConfigWindow.py
Source/ProcessL1aDALEC.py

Added raw data file check before creating L1A hdf5 file

Dalec Update

---

Source/ProcessL1aqc.py

Added minor changes to ProcessL1aqc.py after testing recent dev changes on DALEC branch

Minor Update on Dalec Branch

---

Main.py
Source/ProcessL1aDALEC.py
Source/ProcessL1aqc.py

- Converts relAZ into absolute value and added SZA filter in ProcessL1aDALEC.py
- Minor comment change inrelAZ output in ProcessL1aqc.py

DALEC Updates

---

Source/raw_Data_Hourly_Cutter.py

Added script raw_Data_Hourly_Cutter.py to cut DALEC raw data into hourly files

Added Dalec Raw Data File Cutter Script to Source

---

Source/ProcessL2.py

xBreakdownUNC added L1543
